# Generated by Django 5.0.6 on 2024-05-23 12:39

import hadoop_test1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadoop_test1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDFSFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(storage=hadoop_test1.models.HDFSStorage(), upload_to='hdfs_files')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
